# Generated by Django 5.0.6 on 2024-05-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="content",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="work_interaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="transcripts.workinteraction",
            ),
        ),
    ]
